version: '3.9'
services:
  spark-master:
    container_name: master
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    volumes:
      - /home/ubuntu/data_engineer/:/spark-jobs
    ports:
      - "8080:8080"
      - "7077:7077"
  spark-worker-1:
    container_name: worker-1
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_PORT=7077
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_MASTER=spark-master
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_LOCAL_IP=spark-worker-1
    volumes:
      - /home/ubuntu/data_engineer/:/spark-jobs
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
  spark-worker-2:
    container_name: worker-2
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_PORT=7077
      - SPARK_WORKER_WEBUI_PORT=8082
      - SPARK_MASTER=spark-master
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_LOCAL_IP=spark-worker-2
    volumes:
      - /home/ubuntu/data_engineer/:/spark-jobs
    depends_on:
      - spark-master
    ports:
      - "8082:8082"
  spark-worker-3:
    container_name: worker-3
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_PORT=7077
      - SPARK_WORKER_WEBUI_PORT=8083
      - SPARK_MASTER=spark-master
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_LOCAL_IP=spark-worker-3
    volumes:
      - /home/ubuntu/data_engineer/:/spark-jobs
    depends_on:
      - spark-master
    ports:
      - "8083:8083"
